#/KSU ECHO MESSAGE
messages:
  ksu-command-response: "<green>Go Owls!"

#RANKS AND PRICING
ranks:
  D:
    next_rank: C
    price: 18000
  C:
    next_rank: B
    price: 50000
  B:
    next_rank: A
    price: 190000
  A:
    next_rank: K
    price: 500000
  K:
    next_rank: S
    price: 1300000
  S:
    next_rank: U
    price: 2500000

# Define cell rental prices and durations by region
cells:
  d:
    price: 1000       # Price for D cells
    duration: 7       # Duration in days for renting D cells
  c:
    price: 1500       # Price for C cells
    duration: 7       # Duration in days for renting C cells
  b:
    price: 2500       # Price for B cells
    duration: 7       # Duration in days for renting B cells
  a:
    price: 4000       # Price for A cells
    duration: 7       # Duration in days for renting A cells

#ITEMS AND PRICING
sellable-items:
  COBBLESTONE:
    price: 1.00
  OAK_LOG:
    price: 1.20
  IRON_INGOT:
    price: 7.70
  IRON_ORE:
    price: 4.60
  COAL:
    price: 3.40
  LAPIS_LAZULI:
    price: 2.80
  GOLD_INGOT:
    price: 3.90
  GOLD_ORE:
    price: 3.55
  CACTUS:
    price: 0.32
  DIAMOND:
    price: 50.00
  SANDSTONE:
    price: 1.00
  MELON:
    price: 6.00
  PUMPKIN:
    price: 5.00
  EMERALD:
    price: 70.00
  REDSTONE:
    price: 0.30
  BIRCH_LOG:
    price: 2.00
  NETHERRACK:
    price: 1.40
  SNOW_BLOCK:
    price: 0.50
  SNOWBALL:
    price: 0.10

